# Generated by Django 5.0 on 2024-01-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("creator", models.CharField(blank=True, max_length=100)),
                ("rating", models.FloatField()),
                ("episodes", models.IntegerField()),
                ("aired", models.DateField()),
                ("ended", models.DateField()),
            ],
        ),
    ]
