openapi: 3.0.3
info:
  title: Django DRF Anime Review Platform
  version: 0.0.0
paths:
  /api/creator/:
    get:
      operationId: api_creator_retrieve
      description: A simple viewset for viewing all categories
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        "200":
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
